### PR TITLE
Update Server.hs

### PR DESCRIPTION
**Pull request by instinctive**
Building library for json-relay-0.0..
src/JsonRelay/Server.hs:92:34: error:
    • Couldn't match expected type ‘Foreign.C.Types.CInt’
                  with actual type ‘IO Foreign.C.Types.CInt’
    • In the first argument of ‘Socket.setCloseOnExecIfNeeded’, namely
        ‘(Socket.fdSocket sock)’

### CODE REVIEW

**Comment by seagreen** [comment]
I appreciate it, but the code works with `network-2.8.0.0` right now, and I'm not ready to upgrade `network` yet.
